#!/usr/bin/env bash

# set -v

CP="/home/saed/Projects/KLox/target/classes"
CP+=":/home/saed/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.9.21/kotlin-stdlib-1.9.21.jar"
CP+=":/home/saed/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar"

kotlin -classpath "$CP" aadesaed.gyreas.klox.KLoxKt "$@"
